### ISSUE TITLE
After Facebook login it won't redirect anywhere

### ISSUE THREAD

**Issue by saulodefaria** [SleepWalker/hoauth#21] opened 2013-09-24 07:27 UTC
Hey guys,

Have anyone had this problem? The thing is that, when you are not connected to your facebook account, when you try to authenticate in your website, it opens the login page of facebook, but when you submit your email/password, it leaves you there in a blank page. It logs in though, because if you try again to click on "Login with Facebook" it will work.

Any ideas?

**Comment by SleepWalker** [comment] 2013-09-27 05:50
Yes, this is a bug of HybridAuth. I have tried to fix it, but it has a strange behavior. Even when you not logged in on facebook sometimes it logins you correctly and sometimes not (because of infinity redirection, that caused by broken session vars on the last step of authentication).

**Comment by drew1two** [comment] 2013-09-30 12:33
Yes'm, this does seem to be a problem.
Before I closed my browser I was getting the blank page as well with only this script that was trying to execute:-
window.opener.location.reload();
                    window.close();
This being in HOAuthAction.php, line 266 - 269.
It does execute Yii::app()->end(); immediately afterwards.  **Shrugs....maybe?

After closing the browser and xampp, then restarting everything, I now get the following error when I click on the 'login with facebook' link:-

"You cannot access this page directly."

the URL is http://localhost/test/user/login/oauth?hauth.start=Facebook&hauth.time=1380543794

This URL is where the facebook login is taking me now.  Could this also be a part of broken session vars?

Hope this helps.

**Comment by SleepWalker** [comment] 2013-10-04 12:22
That lines is not a mistake (266 - 269). This is for closing of the window after successful authentication

and about "You cannot access this page directly." this is strange, because facebook brings you there with redirect (i.e. not directly). Probably you pushed 'enter' key in location bar oder something similar?

I will try to catch this bug, or change auth lib, but I can't do this instantly now( I have another work

When you will find something for this problem, please post me here

**Comment by saulodefaria** [comment] 2013-10-05 01:10
Did you guys see this?
https://developers.facebook.com/bugs/501708806589323

Maybe a solution?

**Comment by saulodefaria** [comment] 2013-11-28 19:17
Hi guys, just for the record, it suddenly started working normally. I think we can close this issue.

**Comment by SleepWalker** [comment] 2013-12-16 19:28
nice to hear that!

**Closed as completed by SleepWalker** 2013-12-16 19:28 UTC
